Change simple.ork load location in examples
SilentSys/orhelper pull request #6
Opened 2022-02-11 03:16 UTC by SiboVG

As a complete noob to orhelper, I had some trouble getting just a basic example script to work, I kept getting a 'FileNotFoundError' for the design file. The problem was that the example files take 'examples/simple.ork' as the default location for the .ork file, but if I run the script, that is already inside the examples-directory, the script looked for simple.ork inside 'examples/examples.ork' which just threw the exception.

So I just removed the extra examples-directory reference so that the example files look for simple.ork inside their relative directory, which is already the examples-directory.

Note: again, I have close to zero experience with orhelper, so I'm sorry if this is a bogus PR.

2022-04-03 22:47 UTC, SiboVG commented
@SilentSys does this PR make any sense?

2022-04-06 00:37 UTC, SilentSys commented
Sorry for the delay.

I'm assuming you were running the examples with OrHelper installed through pip?

If I remember correctly, the reasoning for this was to allow people to clone the repo, make changes, and run the examples using the cloned OrHelper. In this case, you are not able to run from within the examples directory because python can't recognize modules from parent directories.

I agree that this can be unintuitive to people who have OrHelper installed and are just trying to run the examples. So maybe the ideal solution involves using something like `os.path.dirname(__file__)` to always get the correct path in all use cases.

2022-04-06 00:40 UTC, SilentSys commented on examples/lazy.py
> +    doc = orh.load_doc('simple.ork')
```suggestion
    doc = orh.load_doc(os.path.join(os.path.dirname(__file__), 'simple.ork'))
```

2022-04-10 18:53 UTC, SilentSys requested changes
You will need to make those changes to the other two files as well.

2023-01-26 09:43 UTC, SiboVG commented
Sorry @SilentSys I really lost track of this. The file locations in the other two files should be fixed now.

2024-02-05 11:28 UTC, SiboVG commented
@SilentSys care to merge this change?

2025-10-23 21:36 UTC, closed without merging